---
# tasks file for roles/zerovm
- apt: name=python-software-properties state=installed

- apt_repository: repo=ppa:zerovm-ci/zerovm-latest
- apt: name=zerovm     state=installed
- apt: name=zerovm-cli state=installed
