---
- hosts: nginx
  gather_facts: false
  tags: nginx
  roles:
    - {role: nginx}

- hosts: nginx-lb
  gather_facts: false
  tags: nginx-lb
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: host08, weight: 1}, {hostname: host09, weight: 1}]}
