---
- hosts: ngnx01:ngnx02
  tags: nginx
  roles: [nginx]

- hosts: ngnx03
  tags: nginx
  roles:
  - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: ngnx01, weight: 1}, {hostname: ngnx02, weight: 1}]}
