---
- hosts: all
  tasks:
  - block:
    - apt_repository: repo='deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main' state=present
    - apt_key: url=https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
  - block:
    - apt_repository: repo='deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic main' state=present
    - apt_key: url=https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
- hosts: host40
  tasks:
  - block:
      - apt: name=salt-master
- hosts: all
  tasks:
  - block:
      - apt: name=salt-minion
