---
- hosts: host03
  tags:  [apache, dokuwiki, redis-server, kore]
  roles: [apache, dokuwiki, redis-server, kore]

- hosts: all
  tags:  default
  roles:
    - all
    - fail2ban
    - { role: ubuntu, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu'}
    - { role: debian, emacs: emacs23-nox, when: ansible_distribution == 'Debian' and ansible_distribution_version ==  "7.8" }

- hosts: host21:host22
  tags:  [postfix, opsmatic]
  roles: [postfix, opsmatic]

- hosts: host04
  tags: tugboat
  roles: [tugboat]

- hosts: host05:host06
  tags:  [nginx]
  roles: [nginx]

- hosts: host07
  tags:  [nginx-lb]
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: host05, weight: 1}, {hostname: host06, weight: 1}]}
