---
- hosts: all
  tags: all
  roles:
    - fail2ban
    - { role: ubuntu, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu'}
    - { role: debian, emacs: emacs23-nox, when: ansible_distribution == 'Debian'}

- hosts: all
  tags: all
  roles: [users, afsin]

- hosts: host03:host40
  tags: ansible
  roles: [apache, dokuwiki, redis-server, swi-prolog, ansible]
  tasks:
    - apt: name=git state=present

- hosts: host21:host22:host41:host42:host43:host44
  tags: postfix
  roles: [postfix]

- hosts: gocd01
  tags: gocd
  roles:
    - gocd-server

- hosts: gocd02
  tags: gocd
  roles:
    - gocd-agent

- hosts: ngnx01:ngnx02
  tags: nginx
  roles: [nginx]

- hosts: ngnx03
  tags: nginx
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: ngnx01, weight: 1}, {hostname: ngnx02, weight: 1}]}
