---
- hosts: host50
  tasks:
  - block:
    - apt_repository: repo=ppa:swi-prolog/stable
    - apt: name={{ item }}
      with_items:
      - httpie
      - swi-prolog
      - git
    when: ansible_os_family == 'Debian'

- hosts: all
  tasks:
  - block:
    - apt: name=aptitude
    - apt: update_cache=yes cache_valid_time=86400
    when: ansible_os_family == 'Debian'
  roles:
  - { role: fail2ban, when: ansible_os_family == 'Debian'}
  - { role: debian, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'}
  - { role: debian, emacs: emacs-nox,   when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'}
