---
- hosts: all
  tags: default
  roles:
    - all
    - { role: centos, when: ansible_distribution == 'CentOS' }
    - { role: debian, when: ansible_distribution == 'Debian' }
    - { role: ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: fedora, when: ansible_distribution == 'Fedora' }
    - afsin

- hosts: docker
  tags: docker
  roles:
    - docker

- hosts: duo
  tags: duo
  roles:
    - duo
    - atilla
    - cem
    - sarah

- hosts: fail2ban
  tags: fail2ban
  roles:
    - fail2ban

- hosts: monit
  tags: monit
  roles:
    - monit

- hosts: postfix
  tags: postfix
  roles:
    - postfix

- hosts: host10:host11:host08
  tags: cem
  roles:
  - cem

- hosts: nginx
  tags: nginx
  roles:
    - {role: nginx}

- hosts: nginx-lb
  tags: nginx-lb
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: host08, weight: 1}, {hostname: host09, weight: 1}]}
