---
- hosts: all
  tags: default
  roles:
    - all
    - monit

- hosts: all:!host08
  tags: default
  roles:
    - { role: ubuntu, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "14.04"}

- hosts: host08
  tags: default
  roles:
    - { role: debian, emacs: emacs23-nox, when: ansible_distribution == 'Debian' and ansible_distribution_version == "7.8" }

- hosts: all
  tags: afsin
  roles:
    - afsin

- hosts: host08:host10:host11
  tags: cem
  roles:
    - cem

- hosts: host08
  tags: sarah
  roles:
    - sarah

- hosts: all:!host10:!host11
  tags: fail2ban
  roles:
    - fail2ban

- hosts: host01:host02
  tags: postfix
  roles:
    - postfix

- hosts: host05:host06
  tags: nginx
  roles:
    - {role: nginx}

- hosts: host04
  tags: nginx-lb
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: host05, weight: 1}, {hostname: host06, weight: 1}]}
