---
- hosts: host04
  tags: docker
  roles:
    - docker

- hosts: host03
  tags:
    - apache
    - dokuwiki
    - redis-server
  roles:
    - apache
    - dokuwiki
    - redis-server

- hosts: all
  tags: default
  roles:
    - all
    - fail2ban
    - afsin

- hosts: all
  tags: default
  roles:
    - { role: ubuntu, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "14.04"}
    - { role: ubuntu, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "15.04"}
    - { role: debian, emacs: emacs23-nox, when: ansible_distribution == 'Debian' and ansible_distribution_version == "7.8" }

- hosts: host08
  tags: 
    - cem
    - sarah
  roles:
    - cem
    - sarah

- hosts: host01:host02
  tags: postfix
  roles:
    - postfix

- hosts: host05:host06
  tags: nginx
  roles:
    - {role: nginx}

- hosts: host07
  tags: nginx-lb
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: host05, weight: 1}, {hostname: host06, weight: 1}, {hostname: host07, weight: 1}]}
