---
- hosts: all
  tags:  default
  roles:
    - all
    - fail2ban
    - { role: ubuntu, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu'}
    - { role: debian, emacs: emacs23-nox, when: ansible_distribution == 'Debian' and ansible_distribution_version ==  "7.8" }
    - afsin

- hosts: rancher-agent
  tags: rancher
  roles: [rancher-agent]

- hosts: rancher-server
  tags: rancher
  roles: [rancher-server]
  
- hosts: hyper
  tags: hyper
  roles: [hyper]

- hosts: host03:host33
  tags:  [apache, dokuwiki, redis-server]
  roles: [apache, dokuwiki, redis-server]

- hosts: postfix
  tags:  [postfix]
  roles: [postfix]

- hosts: host05:host06
  tags:  [nginx]
  roles: [nginx]

- hosts: host07
  tags:  [nginx-lb]
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: host05, weight: 1}, {hostname: host06, weight: 1}]}

- hosts: host08:host38
  tags: users
  roles: [cem, sarah]

- hosts: host12
  tags: users
  roles: [atilla]

- hosts: teamspeak
  tags: teamspeak
  roles: [atilla, teamspeak]
