---
- hosts: all:!host08
  tags: default
  roles:
    - all
    - { role: ubuntu, emacsnox: emacs24-nox, when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "14.04" }
    - monit

- hosts: host08
  tags: default
  roles:
    - all
    - { role: debian, emacsnox: emacs23-nox, when: ansible_distribution == 'Debian' and ansible_distribution_version == "7.8" }
    - monit

- hosts: all
  tags: afsin
  roles:
    - afsin

- hosts: all:!host10:!host11
  tags: fail2ban
  roles:
    - fail2ban

- hosts: host01:host02
  tags: postfix
  roles:
    - postfix

- hosts: nginx
  tags: nginx
  roles:
    - {role: nginx}

- hosts: nginx-lb
  tags: nginx-lb
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: host08, weight: 1}, {hostname: host09, weight: 1}]}
