---
- hosts: all
  tags: upgrade
  tasks:
    - name: install aptitude
      apt: name=aptitude state=present

    - name: safe-upgrade
      apt: update_cache=yes cache_valid_time=86400 upgrade=yes

- hosts: all
  tags: cleanup
  tasks:
    - name: purge
      shell: for i in `dpkg --list|egrep '^rc'|awk '{print $2}'` ; do dpkg -P $i ; done

    - name: autoclean
      command: apt-get -y autoclean

    - name: autoremove
      command: apt-get -y autoremove

    - name: clean
      command: apt-get clean
- hosts: all
  tags: all
  roles:
    - fail2ban
    - { role: ubuntu, emacs: emacs24-nox, when: ansible_distribution == 'Ubuntu'}
    - { role: debian, emacs: emacs23-nox, when: ansible_distribution == 'Debian'}

- hosts: all
  tags: all
  roles: [users, afsin]

- hosts: host03:host40
  tags: ansible
  roles: [apache, dokuwiki, redis-server, swi-prolog, ansible]
  tasks:
    - apt: name=git state=present

- hosts: host41:host43
  tags: postfix
  roles: [postfix]

- hosts: gocd01
  tags: gocd
  roles:
    - gocd-server

- hosts: gocd02
  tags: gocd
  roles:
    - gocd-agent

- hosts: ngnx01:ngnx02
  tags: nginx
  roles: [nginx]

- hosts: ngnx03
  tags: nginx
  roles:
    - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: ngnx01, weight: 1}, {hostname: ngnx02, weight: 1}]}

- hosts: host45
  tags: netbox
  roles:
    - netbox

- hosts: host03
  tags: hacking
  tasks:
    - apt: name=nmap
    - apt: name=python-nmap
    - apt: name=ftpd
    - apt: name=python-socketio-client
