---
- include: all.yml
- include: distributions.yml
- include: docker.yml
- include: duo.yml
- include: gateone.yml
- include: postfix.yml
- include: users.yml
- include: zabbix-server.yml
- include: zabbix-agent.yml
- include: zfs.yml
- include: fail2ban.yml
- include: munin.yml
