---
- hosts: host40
  tasks:
  - block:
    - apt_repository: repo=ppa:swi-prolog/stable
    - apt: update_cache=yes cache_valid_time=86400
    - apt: name={{ item }}
      with_items:
      - httpie
      - swi-prolog
      - git
    - pip: name=httpstat
    when: ansible_os_family == 'Debian'

- hosts: all
  tasks:
  - block:
    - apt: name=aptitude
    - shell: for i in `dpkg --list|egrep '^rc'|awk '{print $2}'` ; do dpkg -P $i ; done
    - command: apt-get -y autoclean
    - command: apt-get -y autoremove
    - command: apt-get clean
    when: ansible_os_family == 'Debian'
  - block:
    - apt: name=aptitude
    - shell: for i in `dpkg --list|egrep '^rc'|awk '{print $2}'` ; do dpkg -P $i ; done
    - command: apt-get -y autoclean
    - command: apt-get -y autoremove
    - command: apt-get clean
    when: ansible_os_family == 'Ubuntu'
  roles:
  - { role: fail2ban, when: ansible_os_family == 'Debian'}
  - { role: ubuntu, emacs: emacs24-nox, when: ansible_os_family == 'Debian'}

- hosts: all
  tags: users
  roles: [users, afsin]

- hosts: host41:host43
  tags: postfix
  roles: [postfix]

- hosts: ngnx01:ngnx02
  tags: nginx
  roles: [nginx]

- hosts: ngnx03
  tags: nginx
  roles:
  - {role: nginx-lb, domain: toparlak.de, nginx_hosts: [{hostname: ngnx01, weight: 1}, {hostname: ngnx02, weight: 1}]}
