---
- hosts: all
  tasks:
    - name: install aptitude
      apt: name=aptitude state=present

    - name: safe-upgrade
      apt: update_cache=yes cache_valid_time=86400 upgrade=yes

    - name: purge
      shell: for i in `dpkg --list|egrep '^rc'|awk '{print $2}'` ; do dpkg -P $i ; done

    - name: autoclean
      command: apt-get -y autoclean

    - name: autoremove
      command: apt-get -y autoremove

    - name: clean
      command: apt-get clean
