---
- hosts: all
  remote_user: root
  tasks:
    - apt: update_cache=yes cache_valid_time=86400 upgrade=dist
    - script: scripts/dpkg-p.sh
    - command: apt-get -y autoclean
    - command: apt-get -y autoremove
    - command: apt-get clean
