---
- hosts: duo
  remote_user: root
  gather_facts: false
  tags: users
  roles:
  - atilla
  - cem
  - sarah

- hosts: all
  remote_user: root
  gather_facts: false
  tags: users
  roles:
  - afsin
