---
- apt_key:         url='https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub' state=present
- apt_repository: repo='deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main'        state=present
- apt:            name=salt-master
- apt:            name=salt-minion
- copy:           src=minion dest=/etc/salt/minion
