---
    - apt: name={{ item }} state=installed
      with_items:
        - postfix
        - postfix-policyd-spf-python
        - spamassassin
        - spamc
        - dovecot-core
        - dovecot-imapd
        - dovecot-pop3d
        - dovecot-managesieved
        - dovecot-sieve

    - group: name=spamd

    - user: name=spamd home=/var/log/spamassassin shell=/bin/false group=spamd

    - lineinfile: dest=/etc/default/spamassassin backrefs=yes regexp='^ENABLED=0' line='ENABLED=1'
    - lineinfile: dest=/etc/default/spamassassin backrefs=yes regexp='^CRON=0' line='CRON=1'
    - lineinfile: dest=/etc/default/spamassassin backrefs=yes regexp='^OPTIONS="--create-prefs --max-children 5 --helper-home-dir"' line='OPTIONS="-4 --create-prefs --max-children 2 --username spamd -H ${SAHOME} -s ${SAHOME}spamd.log"'

    - lineinfile: dest=/etc/default/spamassassin insertbefore='^OPTIONS=' line='SAHOME="/var/log/spamassassin/"'

    - lineinfile:  dest=/etc/spamassassin/local.cf regexp='^# rewrite_header Subject \*\*\*\*\*SPAM\*\*\*\*\*' line='rewrite_header Subject *****SPAM*****' backrefs=yes

    - service: name=spamassassin state=started
      notify:
        - restart postfix

    - copy: src=virtual dest=/etc/postfix/virtual
      notify:
        - create virtual.db
        - restart postfix

    - name: create virtual.db
      shell: postmap /etc/postfix/virtual
             creates=/etc/postfix/virtual.db
      notify:
        - restart postfix

    - template: src=mailname.j2 dest=/etc/mailname mode=0644
      notify:
        - create virtual.db
        - restart postfix

    - lineinfile: dest=/etc/postfix/main.cf regexp='^mydestination = ' line='mydestination = toparlak.de, localhost, localhost.localdomain'
    - lineinfile: dest=/etc/postfix/main.cf regexp='smtpd_recipient_restrictions = reject_unknown_sender_domain, reject_unknown_recipient_domain, reject_unauth_pipelining, permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination' line='smtpd_recipient_restrictions = reject_unknown_sender_domain, reject_unknown_recipient_domain, reject_unauth_pipelining, permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, check_policy_service unix:private/policy-spf'
    - lineinfile: dest=/etc/postfix/main.cf insertafter='EOF' line='inet_protocols = ipv4'
    - lineinfile: dest=/etc/postfix/main.cf insertafter='EOF' line='policy-spf_time_limit = 3600s'
    - lineinfile: dest=/etc/postfix/main.cf insertafter='alias_maps = hash:/etc/aliases' line='virtual_alias_maps = hash:/etc/postfix/virtual'
    - lineinfile: dest=/etc/postfix/main.cf insertafter='alias_database = hash:/etc/aliases' line='myorigin = /etc/mailname'

    - lineinfile: dest=/etc/dovecot/dovecot.conf insertafter='#listen = \*, ::'  line='listen = *'
    - lineinfile: dest=/etc/dovecot/dovecot.conf insertafter='EOF' line='protocols = pop3 imap'

    - lineinfile: dest=/etc/postfix/master.cf insertafter='EOF' line='policy-spf  unix  -       n       n       -       -       spawn'
    - lineinfile: dest=/etc/postfix/master.cf insertafter='policy-spf  unix  -       n       n       -       -       spawn' line='  user=nobody argv=/usr/bin/policyd-spf'
    - lineinfile: dest=/etc/postfix/master.cf insertafter='smtp      inet  n       -       -       -       -       smtpd' line='  -o content_filter=spamassassin'
    - lineinfile: dest=/etc/postfix/master.cf insertafter='EOF' line='spamassassin unix -     n       n       -       -       pipe'
    - lineinfile: dest=/etc/postfix/master.cf insertafter='spamassassin unix -     n       n       -       -       pipe' line='  user=spamd argv=/usr/bin/spamc -f -e'
    - lineinfile: dest=/etc/postfix/master.cf insertafter='  user=spamd argv=/usr/bin/spamc -f -e' line='  /usr/sbin/sendmail -oi -f ${sender} ${recipient}'
