---
    - name: install apt packages
      apt: name={{ item }} state=installed
      with_items:
        - dovecot-postfix
        - postfix-policyd-spf-python
        - spamassassin
        - spamc

    - name: group spamd
      group: name=spamd

    - name: user spamd
      user: name=spamd home=/var/log/spamassassin shell=/bin/false group=spamd
      
    - name: customize /etc/default/spamassassin
      lineinfile: dest=/etc/default/spamassassin regexp='^ENABLED=0' line='ENABLED=1' backrefs=yes

    - name: customize /etc/default/spamassassin
      lineinfile: dest=/etc/default/spamassassin regexp='^CRON=0' line='CRON=1' backrefs=yes

    - name: customize /etc/default/spamassassin
      lineinfile: dest=/etc/default/spamassassin regexp='^OPTIONS="--create-prefs --max-children 5 --helper-home-dir"' line='OPTIONS="--create-prefs --max-children 2 --username spamd -H ${SAHOME} -s ${SAHOME}spamd.log"' backrefs=yes

    - name: customize /etc/default/spamassassin
      lineinfile: dest=/etc/default/spamassassin insertbefore='^OPTIONS=' line='SAHOME="/var/log/spamassassin/"'

    - name: customize /etc/spamassassin/local.cf
      lineinfile:  dest=/etc/spamassassin/local.cf regexp='^# rewrite_header Subject \*\*\*\*\*SPAM\*\*\*\*\*' line='rewrite_header Subject *****SPAM*****' backrefs=yes

    - name: copy virtual
      copy: src=virtual dest=/etc/postfix/virtual
      notify:
        - create virtual.db
        - restart postfix

    - name: copy mailname
      template: src=mailname.j2 dest=/etc/mailname mode=0644
      notify:
        - create virtual.db
        - restart postfix

    - name: customize /etc/postfix/main.cf
      lineinfile: dest=/etc/postfix/main.cf regexp='^mydestination = ' line='mydestination = host01.uxxa.eu, host02.uxxa.eu, uxxa.eu, toparlak.de, localhost, localhost.localdomain'

    - name: customize /etc/postfix/main.cf 
      lineinfile: dest=/etc/postfix/main.cf regexp='smtpd_recipient_restrictions = reject_unknown_sender_domain, reject_unknown_recipient_domain, reject_unauth_pipelining, permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination' line='smtpd_recipient_restrictions = reject_unknown_sender_domain, reject_unknown_recipient_domain, reject_unauth_pipelining, permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, check_policy_service unix:private/policy-spf'

    - name: customize /etc/postfix/main.cf
      lineinfile:  dest=/etc/postfix/main.cf insertafter='EOF' line='inet_protocols = ipv4'

    - name: customize /etc/postfix/main.cf
      lineinfile:  dest=/etc/postfix/main.cf insertafter='EOF' line='policy-spf_time_limit = 3600s'

    - name: customize /etc/postfix/main.cf
      lineinfile:  dest=/etc/postfix/main.cf insertafter='alias_maps = hash:/etc/aliases' line='virtual_alias_maps = hash:/etc/postfix/virtual'

    - name: customize /etc/postfix/main.cf
      lineinfile:  dest=/etc/postfix/main.cf insertafter='alias_database = hash:/etc/aliases' line='myorigin = /etc/mailname'

    - name: customize /etc/dovecot/dovecot.conf
      lineinfile: dest=/etc/dovecot/dovecot.conf insertafter='#listen = \*, ::'  line='listen = *'

    - name: customize /etc/dovecot/dovecot.conf
      lineinfile:  dest=/etc/dovecot/dovecot.conf insertafter='EOF' line='protocols = pop3 imap'

    - name: customize /etc/postfix/master.cf
      lineinfile:  dest=/etc/postfix/master.cf insertafter='EOF' line='policy-spf  unix  -       n       n       -       -       spawn'

    - name: customize /etc/postfix/master.cf
      lineinfile:  dest=/etc/postfix/master.cf insertafter='policy-spf  unix  -       n       n       -       -       spawn' line='  user=nobody argv=/usr/bin/policyd-spf'

    - name: customize /etc/postfix/master.cf
      lineinfile:  dest=/etc/postfix/master.cf insertafter='smtp      inet  n       -       -       -       -       smtpd' line='  -o content_filter=spamassassin'

    - name: customize /etc/postfix/master.cf
      lineinfile:  dest=/etc/postfix/master.cf insertafter='EOF' line='spamassassin unix -     n       n       -       -       pipe'

    - name: customize /etc/postfix/master.cf
      lineinfile:  dest=/etc/postfix/master.cf insertafter='spamassassin unix -     n       n       -       -       pipe' line='  user=spamd argv=/usr/bin/spamc -f -e'

    - name: customize /etc/postfix/master.cf
      lineinfile:  dest=/etc/postfix/master.cf insertafter='  user=spamd argv=/usr/bin/spamc -f -e' line='  /usr/sbin/sendmail -oi -f ${sender} ${recipient}'
