---
- apt: update_cache=yes cache_valid_time=86400

- name: install apt packages
  apt: name={{ item }} state=installed
  with_items:
    - atop
    - bmon
    - ccze
    - facter
    - fish
    - htop
    - iftop
    - libmodern-perl-perl
    - mailutils
    - mc
    - netcat
    - nmap
    - traceroute
    - tmux
    - zsh

- apt: name={{ emacs }} state=installed
- apt: name={{ item }} state=installed
  with_items:
    - yaml-mode

- name: disable ipv6
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/sysctl.d/disable-ipv6.conf

- name: set timezone
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/timezone
  notify:
    - update timezone
