---
- name: install apt packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - apache2
    - facter
    - htop
    - python-keyczar
    - tmux
    - yaml-mode
    - zsh
    - mc
    - mailutils

- apt: name={{ emacs }} state=installed

- name: disable ipv6
  copy: src={{ item }}  dest=/{{ item }}
  with_items:
    - etc/sysctl.d/disable-ipv6.conf

- name: set dns-search string
  lineinfile: dest=/etc/network/interfaces regexp='^[     ]*dns-search.*' line='        dns-search toparlak.de'
  notify:
    - resolvconf update
