---
- apt_repository: repo='deb http://repo.zabbix.com/zabbix/2.2/debian/ wheezy main' state=present
  when: ansible_distribution == "Debian"

- apt_key: url='http://repo.zabbix.com/zabbix-official-repo.key' state=present
  when: ansible_distribution == "Debian"

- name: install apt packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - zabbix-agent

- name: customize /etc/zabbix/zabbix_agentd.conf
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server=.*$' line='Server=127.0.0.1,{{ zabbix_server }}' backrefs=yes
  notify:
    - restart zabbix-agent

- name: customize /etc/zabbix/zabbix_agentd.conf
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^ServerActive=.*$' line='ServerActive=127.0.0.1,{{ zabbix_server }}' backrefs=yes
  notify:
    - restart zabbix-agent

- name: customize /etc/zabbix/zabbix_agentd.conf
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=.*$' line='Hostname={{ inventory_hostname }}' backrefs=yes
  notify:
    - restart zabbix-agent
