---
- group: name=sarah
         gid=5003

- user: name=sarah
        comment='Sarah Sagemueller'
        password='$6$Qukw9YQ0$xWqQsSXTk1A8AkOBqEDAEZU.I6uxIkA2u1GfEOMJbMn3BOWA52b3PCo0nXWdFy3irAv86L0tQ2tgYtn2xwlcu/'
        shell=/bin/bash
        uid=5003
        group=sarah
