---
- group: name=afsin
         gid=5000

- user: name=afsin
        comment='Afsin Toparlak'
        shell=/bin/zsh
        password='$1$A.OAhdOI$sIONMKC.56TPVaDRPln8G1'
        uid=5000
        group=afsin

- file: dest=/home/afsin/.ssh
        state=directory
        owner=afsin
        group=afsin
        mode=0700

- copy: src={{ item }} owner=afsin group=afsin dest=/home/afsin/{{ item }}
  with_items:
    - .ssh/authorized_keys
    - .ssh/config
    - .emacs
    - .tmux.conf
    - .gitignore
    - .gitconfig
    - .screenrc

# the following private is secured with a passphrase
#
- copy: dest=/home/afsin/.ssh/id_rsa
        src=.ssh/id_rsa
        owner=afsin
        group=afsin
        mode=600

- copy: dest=/etc/sudoers.d/afsin
        src=sudoers.d
        mode=0440

- template: dest=/home/afsin/.zshrc
            src=.zshrc.j2
            owner=afsin
            group=afsin

- file: dest=/home/afsin/tmp
        state=directory
        owner=afsin
        group=afsin

- template: dest=/home/afsin/tmp/foo
            src=foo.j2
            owner=afsin
            group=afsin
