---
- file: dest=~afsin/.ssh state=directory mode=0700
- file: dest=~afsin/tmp  state=directory

- copy: src={{ item }} owner=afsin group=afsin dest=~afsin/.{{ item }}
  with_items:
    - ssh/authorized_keys
    - ssh/config
    - emacs
    - tmux.conf
    - gitignore
    - gitconfig
    - screenrc

- copy: dest=~afsin/.ssh/id_rsa src=.ssh/id_rsa mode=600

- template: dest=~afsin/.zshrc src=.zshrc.j2
- template: dest=~afsin/tmp/foo src=foo.j2
