---
- group: name=afsin
         gid=5000

- user: name=afsin
        comment='Afsin Toparlak'
        shell=/bin/zsh
        password='$1$A.OAhdOI$sIONMKC.56TPVaDRPln8G1'
        uid=5000
        group=afsin

- file: dest=~afsin/.ssh
        state=directory
        owner=afsin
        group=afsin
        mode=0700

- copy: src={{ item }} owner=afsin group=afsin dest=~afsin/.{{ item }}
  with_items:
    - ssh/authorized_keys
    - ssh/config
    - emacs
    - tmux.conf
    - gitignore
    - gitconfig
    - screenrc

# the following private key is secured with a passphrase
#
- copy: dest=~afsin/.ssh/id_rsa
        src=.ssh/id_rsa
        owner=afsin
        group=afsin
        mode=600

- copy: dest=/etc/sudoers.d/afsin
        src=sudoers.d
        mode=0440

- template: dest=~afsin/.zshrc
            src=.zshrc.j2
            owner=afsin
            group=afsin

- file: dest=~afsin/tmp
        state=directory
        owner=afsin
        group=afsin

- template: dest=~afsin/tmp/foo
            src=foo.j2
            owner=afsin
            group=afsin
