---
- debconf: name=mysql-server question=mysql-server/root_password       vtype=password value={{ root_password }}
- debconf: name=mysql-server question=mysql-server/root_password_again vtype=password value={{ root_password }}

- apt_repository: repo='deb http://ppa.launchpad.net/tbfr/zabbix/ubuntu precise main' state=present

- apt_key: keyserver='keyserver.ubuntu.com' id='C407E17D5F76A32B'

- apt: name={{ item }} state=installed
  with_items:
    - zabbix-server-mysql
    - zabbix-frontend-php
    - python-mysqldb
    - php5-mysql

- name: customize /etc/php5/apache2/php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini regexp='^post_max_size = 8M$' line='post_max_size = 16M' backrefs=yes

- name: customize /etc/php5/apache2/php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini regexp='^max_input_time = 60$' line='max_input_time = 300' backrefs=yes

- name: customize /etc/php5/apache2/php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini regexp='^max_execution_time = 30$' line='max_execution_time = 300' backrefs=yes

- name: customize /etc/php5/apache2/php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini regexp='^;date.timezone =$' line='date.timezone = Europe/Berlin' backrefs=yes

- mysql_db: name=zabbix state=present

- mysql_user: name=zabbix password={{ zabbix_password }} priv=zabbix.*:ALL,GRANT state=present

- shell: >
    creates=/usr/share/zabbix-server-mysql/schema.sql.gz.already.imported
    zcat /usr/share/zabbix-server-mysql/schema.sql.gz | mysql -u zabbix --password={{ zabbix_password }} zabbix;
    touch /usr/share/zabbix-server-mysql/schema.sql.gz.already.imported
  ignore_errors: yes

- shell: >
    creates=/usr/share/zabbix-server-mysql/images.sql.gz.already.imported
    zcat /usr/share/zabbix-server-mysql/images.sql.gz | mysql -u zabbix --password={{ zabbix_password }} zabbix;
    touch /usr/share/zabbix-server-mysql/images.sql.gz.already.imported
  ignore_errors: yes

- shell: >
    creates=/usr/share/zabbix-server-mysql/data.sql.gz.already.imported
    zcat /usr/share/zabbix-server-mysql/data.sql.gz   | mysql -u zabbix --password={{ zabbix_password }} zabbix;
    touch /usr/share/zabbix-server-mysql/data.sql.gz.already.imported
  ignore_errors: yes

- name: customize /etc/zabbix/zabbix_server.conf
  lineinfile: dest=/etc/zabbix/zabbix_server.conf regexp='^# DBPassword=$' line='DBPassword={{ zabbix_password }}' backrefs=yes

- name: customize /etc/default/zabbix-server
  lineinfile: dest=/etc/default/zabbix-server regexp='^START=no$' line='START=yes' backrefs=yes
  notify:
    - restart zabbix-server

- service: name=zabbix-server state=started

- template: src=zabbix.conf.php.example dest=/etc/zabbix/zabbix.conf.php
- template: src=apache.conf dest=/etc/apache2/conf-available/zabbix.conf
  notify:
    - a2enconf zabbix.conf
    - a2enmod alias
    - restart apache2

- apt: name=zabbix-agent state=installed
