---
- name: ansible repo
  apt_repository: repo=ppa:ansible/ansible

- name: install apt packages
  apt: name={{ item }} state=installed
  with_items:
    - facter
    - htop
    - lynx
    - nmap
    - python-keyczar
    - python-zmq
    - python-pycurl
    - sshpass
    - tmux
    - traceroute
    - yaml-mode
    - zsh
    - unzip
    - psmisc
    - vim
    - mc
    - mailutils

- apt: name={{ emacsnox }} state=installed

- name: disable ipv6
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/sysctl.d/disable-ipv6.conf

- name: set timezone
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/timezone
  notify:
    - update timezone

- name: set dns search string
  lineinfile: dest=/etc/network/interfaces regexp='^[     ]*dns-search.*' line='        dns-search toparlak.de'
  notify: 
    - restart networking
