---
- name: ansible repo
  apt_repository: repo=ppa:rquillo/ansible

- name: install apt packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - emacs23-nox
    - facter
    - htop
    - lynx
    - nmap
    - python-keyczar
    - python-zmq
    - python-pycurl
    - sshpass
    - tmux
    - traceroute
    - yaml-mode
    - zsh
    - zabbix-agent
    - unzip

- name: disable ipv6
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/sysctl.d/disable-ipv6.conf

- name: set timezone
  copy: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/timezone
  notify:
    - update timezone

- name: set dns search string
  lineinfile: dest=/etc/network/interfaces regexp='^[     ]*dns-search.*' line='        dns-search uxxa.eu toparlak.de'
  notify: 
    - restart networking

- name: customize /etc/zabbix/zabbix_agentd.conf
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server=127.0.0.1$' line='Server={{ zabbix_server }}' backrefs=yes
  notify:
    - restart zabbix-agent

- name: customize /etc/zabbix/zabbix_agentd.conf
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^ServerActive=127.0.0.1$' line='ServerActive={{ zabbix_server }}' backrefs=yes
  notify:
    - restart zabbix-agent

- name: customize /etc/zabbix/zabbix_agentd.conf
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=Zabbix server$' line='Hostname={{ inventory_hostname }}' backrefs=yes
  notify:
    - restart zabbix-agent
