---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart networking
  command: service networking restart

- name: restart zabbix-agent
  command: service zabbix-agent restart
