---
- group: name=cem
         gid=5002

- user: name=cem
        comment='Cem Toparlak'
        shell=/bin/bash
        password='$6$pcr9h0DR$5/dRQIgpD42PjjCKRCJktqLqN6vGhn8bv2iTd/eyl3IQIl/noyYMezpJwM2JdVPDb8ROzJsjgriL2qhWfiWbO0'
        uid=5002
        group=cem

- copy: src=.bashrc   dest=/home/cem/.bashrc
- copy: src=sudoers.d dest=/etc/sudoers.d/cem
        mode=0440
