if [ $TTY ] ; then

    HISTFILE=~/.zhistory
    SAVEHIST=200000
    HISTSIZE=200000

    case $TERM in
	xterm*)
            precmd () {
		if [ "`uname -s`" = "SunOS" ] ; then
		    echo -ne '\ek'$HOST:`basename $PWD`'\e\\'
		fi
		print -Pn "\e]0;%n@%m: %~\a"
	    }
            ;;
    esac
    
    bindkey -e

    unsetopt ignoreeof
    unsetopt printexitvalue

    setopt   autocd
    setopt   autopushd
    setopt   nobeep

    autoload -U is-at-least

    if is-at-least 4.2.1
    then
	autoload -Uz compinit
	setopt incappendhistory
	setopt histappend
	setopt histexpiredupsfirst
	setopt histignorealldups
	setopt histsavenodups
	setopt sharehistory
    else
	autoload -U  compinit
	setopt   appendhistory
    fi
    compinit

    alias lf='ls -FsC'
    alias la='ls -al'
    alias ll='ls -l'
    alias lt='ls -altr'
    
    alias rm='rm -i'
    alias cp='cp -i'
    alias mv='mv -i'
    
    alias a=alias
    alias h=history
    
    alias -- -=popd
    
    export PS1='[ %* ] %B%n@%m:%b%1~ %# '
    export VISUAL=emacs
    export EDITOR=emacs
    
fi

timestamp(){date '+%y%m%d.%H%M'}
acp(){cp -pi $1 $1.`timestamp`}

export PATH=$PATH:~/bin

if [[ -f ~/.zshrc.{{ inventory_hostname }} ]] ; then
   source  ~/.zshrc.{{ inventory_hostname }}
fi
