---
- apt: name={{ item }} state=present
  with_items:
    - fail2ban
  when: ansible_os_family == 'Debian'

- yum: name={{ item }} state=present
  with_items:
    - fail2ban
  when: ansible_os_family == 'RedHat'

- lineinfile: dest=/etc/fail2ban/jail.conf regexp='^bantime *= *(600|3600)$' line='bantime = 86400' backrefs=yes
  notify:
    - restart fail2ban

- lineinfile: dest=/etc/fail2ban/jail.conf regexp='^findtime *= *(600|3600)$' line='findtime = 86400' backrefs=yes
  notify:
    - restart fail2ban
