---
- name: install apt packages
  apt: name={{ item }} state=installed
  with_items:
    - fail2ban

- lineinfile: dest=/etc/fail2ban/jail.conf regexp='^bantime  = 600' line='bantime = 3600' backrefs=yes
  notify:
    - restart fail2ban
    
- lineinfile: dest=/etc/fail2ban/jail.conf regexp='^findtime = 600' line='findtime = 3600' backrefs=yes
  notify:
    - restart fail2ban
