---
- apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
#- apt_key: url='http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x36A1D7869245C8950F966E92D8576A8BA88D21E9' state=present
- apt_key: id=36A1D7869245C8950F966E92D8576A8BA88D21E9 keyserver=p80.pool.sks-keyservers.net

- apt: name=lxc-docker state=installed
- apt: name=python-pip state=installed

- pip: name=docker-py state=present
